import Head from 'next/head'

export default function Home() {
  return (
    <div className='bg-purple-900 p-10'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-center'>Igor</main>

    </div>
  )
}
